name: Bump version

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.DEPLOY_KEY_CI }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          push: false
          # 3: NO_COMMITS_FOUND, 21: NO_INCREMENT
          no_raise: "3"
      - name: Push using ssh
        run: git push --tags origin main
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
        
