name: Bump version

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          #token: "${{ secrets.GITHUB_TOKEN }}"
          ssh-key: "${{ secrets.DEPLOY_KEY_ANON }}"
          #ssh-key: "${{ secrets.DEPLOY_KEY_HKEELER }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        #with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          push: false
      - name: Push using ssh
        run: git push origin main --tags
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
        
